version: '3'

vars:
  TEST_NAMESPACE: pvc-chonker-test
  CHARTS:
    - charts/konductor
    - charts/pvc-chonker
    - charts/secret-santa

tasks:
  validate-all:
    desc: Validate all Helm charts
    cmds:
      - for: { var: CHARTS }
        cmd: helm lint {{.ITEM}}
      - for: { var: CHARTS }
        cmd: helm template {{.ITEM}} --validate

  package:
    desc: Package all Helm charts
    cmds:
      - for: { var: CHARTS }
        cmd: helm package {{.ITEM}}

  dry-run:
    desc: Dry run all Helm charts
    cmds:
      - for: { var: CHARTS }
        cmd: helm install {{.ITEM | base}} {{.ITEM}} --dry-run --debug --namespace {{.TEST_NAMESPACE}}

  lint:
    desc: Lint Helm chart
    cmds:
      - helm lint charts/pvc-chonker

  test:
    desc: Run chart tests
    dir: charts/pvc-chonker
    cmds:
      - task: test-all

  test-all:
    desc: Run all tests (lint + chart tests)
    cmds:
      - task: lint
      - task: test