version: '3'

tasks:
  pvc-chonker:lint:
    desc: Lint pvc-chonker chart
    cmds:
      - helm lint ./charts/pvc-chonker

  pvc-chonker:template:
    desc: Generate pvc-chonker templates
    cmds:
      - helm template pvc-chonker ./charts/pvc-chonker

  pvc-chonker:template-debug:
    desc: Generate pvc-chonker templates with debug
    cmds:
      - helm template pvc-chonker ./charts/pvc-chonker --debug

  pvc-chonker:package:
    desc: Package pvc-chonker chart
    cmds:
      - helm package ./charts/pvc-chonker

  pvc-chonker:dry-run:
    desc: Dry-run pvc-chonker installation
    cmds:
      - helm install pvc-chonker ./charts/pvc-chonker --dry-run --debug

  pvc-chonker:validate:
    desc: Validate pvc-chonker chart
    cmds:
      - task: pvc-chonker:lint
      - task: pvc-chonker:template

  lint-all:
    desc: Lint all charts
    cmds:
      - task: pvc-chonker:lint

  validate-all:
    desc: Validate all charts
    cmds:
      - task: pvc-chonker:validate

  clean:
    desc: Clean packaged charts
    cmds:
      - rm -f *.tgz

  release:install-cr:
    desc: Install chart-releaser binary
    cmds:
      - curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz"
      - tar -xzf cr.tar.gz
      - sudo mv cr /usr/local/bin/cr
      - rm cr.tar.gz

  release:manual:
    desc: Manually release charts (requires GITHUB_TOKEN env var)
    deps: [release:install-cr]
    cmds:
      - cr package charts/pvc-chonker
      - cr upload --owner logicIQ --git-repo helm-charts --token "$GITHUB_TOKEN"
      - cr index --owner logicIQ --git-repo helm-charts --token "$GITHUB_TOKEN" --push