version: '3'

tasks:
  pvc-chonker:lint:
    desc: Lint pvc-chonker chart
    cmds:
      - helm lint ./pvc-chonker

  pvc-chonker:template:
    desc: Generate pvc-chonker templates
    cmds:
      - helm template pvc-chonker ./pvc-chonker

  pvc-chonker:template-debug:
    desc: Generate pvc-chonker templates with debug
    cmds:
      - helm template pvc-chonker ./pvc-chonker --debug

  pvc-chonker:package:
    desc: Package pvc-chonker chart
    cmds:
      - helm package ./pvc-chonker

  pvc-chonker:dry-run:
    desc: Dry-run pvc-chonker installation
    cmds:
      - helm install pvc-chonker ./pvc-chonker --dry-run --debug

  pvc-chonker:validate:
    desc: Validate pvc-chonker chart
    cmds:
      - task: pvc-chonker:lint
      - task: pvc-chonker:template

  lint-all:
    desc: Lint all charts
    cmds:
      - task: pvc-chonker:lint

  validate-all:
    desc: Validate all charts
    cmds:
      - task: pvc-chonker:validate

  clean:
    desc: Clean packaged charts
    cmds:
      - rm -f *.tgz